# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/banet_l/github/stealth-converter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/banet_l/github/stealth-converter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/banet_l/github/stealth-converter/CMakeFiles /home/banet_l/github/stealth-converter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/banet_l/github/stealth-converter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stealth-converter

# Build rule for target.
stealth-converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stealth-converter
.PHONY : stealth-converter

# fast build rule for target.
stealth-converter/fast:
	$(MAKE) -f CMakeFiles/stealth-converter.dir/build.make CMakeFiles/stealth-converter.dir/build
.PHONY : stealth-converter/fast

#=============================================================================
# Target rules for targets named STREAM

# Build rule for target.
STREAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STREAM
.PHONY : STREAM

# fast build rule for target.
STREAM/fast:
	$(MAKE) -f src/stream/CMakeFiles/STREAM.dir/build.make src/stream/CMakeFiles/STREAM.dir/build
.PHONY : STREAM/fast

#=============================================================================
# Target rules for targets named VIDEO_CONVERTER

# Build rule for target.
VIDEO_CONVERTER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VIDEO_CONVERTER
.PHONY : VIDEO_CONVERTER

# fast build rule for target.
VIDEO_CONVERTER/fast:
	$(MAKE) -f src/video-converter/CMakeFiles/VIDEO_CONVERTER.dir/build.make src/video-converter/CMakeFiles/VIDEO_CONVERTER.dir/build
.PHONY : VIDEO_CONVERTER/fast

src/stealth-converter.o: src/stealth-converter.cc.o

.PHONY : src/stealth-converter.o

# target to build an object file
src/stealth-converter.cc.o:
	$(MAKE) -f CMakeFiles/stealth-converter.dir/build.make CMakeFiles/stealth-converter.dir/src/stealth-converter.cc.o
.PHONY : src/stealth-converter.cc.o

src/stealth-converter.i: src/stealth-converter.cc.i

.PHONY : src/stealth-converter.i

# target to preprocess a source file
src/stealth-converter.cc.i:
	$(MAKE) -f CMakeFiles/stealth-converter.dir/build.make CMakeFiles/stealth-converter.dir/src/stealth-converter.cc.i
.PHONY : src/stealth-converter.cc.i

src/stealth-converter.s: src/stealth-converter.cc.s

.PHONY : src/stealth-converter.s

# target to generate assembly for a file
src/stealth-converter.cc.s:
	$(MAKE) -f CMakeFiles/stealth-converter.dir/build.make CMakeFiles/stealth-converter.dir/src/stealth-converter.cc.s
.PHONY : src/stealth-converter.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stealth-converter"
	@echo "... STREAM"
	@echo "... VIDEO_CONVERTER"
	@echo "... src/stealth-converter.o"
	@echo "... src/stealth-converter.i"
	@echo "... src/stealth-converter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

